repositories:
  - name: argocd
    url: https://argoproj.github.io/argo-helm
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
---
releases:
  - name: argocd
    chart: argocd/argo-cd
    version: 7.7.17
    namespace: argocd
    createNamespace: true
    values:
      - values-argocd.yaml

  - name: argocd-apps
    chart: argocd/argocd-apps
    version: 2.0.2
    namespace: argocd
    values:
      - values-argocd-apps.yaml
    needs:
      - argocd

  - name: custom-resources
    chart: ./charts/custom-resources
    version: 0.1.0
    namespace: default
    needs:
      - argocd/argocd-apps

  - name: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 69.3.0
    namespace: monitoring
    createNamespace: true
    values:
      - monitoring/values-monitoring.yaml
      - monitoring/values-prometheus.yaml
      - monitoring/values-alertmanager.yaml
