repositories:
  - name: argocd
    url: https://argoproj.github.io/argo-helm
---
releases:
  - name: argocd
    chart: argo/argo-cd
    version: 7.7.17
    namespace: argocd
    createNamespace: true
    values:
      - values-argocd.yaml
