global:
  domain: argocd.minikube.local
  nodeSelector:
    kubernetes.io/hostname: minikube

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

repoServer:
  rbac:
    - apiGroups:
        - ""
      resources:
        - pods/exec
      verbs:
        - create

configs:
  cm:
    exec:
      enabled: true
    timeout.reconciliation: 1s
  repositories:
    server:
      url: https://github.com/filipegalo/playground_k8s.git
      type: git
      insecure: "true"
      project: playground-k8s
      name: playground_k8s
    kubernetes-dashboard:
      url: https://kubernetes.github.io/dashboard/
      type: helm
      insecure: "true"
      project: playground-k8s
      name: kubernetes-dashboard
