applications:
  nginx:
    namespace: argocd
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: playground-k8s
    destination:
      namespace: nginx
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/filipegalo/playground_k8s.git
      targetRevision: HEAD
      path: charts/nginx
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
  k8s-dashboard:
    namespace: argocd
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: playground-k8s
    destination:
      namespace: k8s-dashboard
      server: https://kubernetes.default.svc
    source:
      repoURL: https://kubernetes.github.io/dashboard/
      chart: kubernetes-dashboard
      targetRevision: "7.10.4"
      helm:
        values: |
          app:
            scheduling:
              nodeSelector:
                node-role.kubernetes.io/apps: ""
            ingress:
              enabled: true
              hosts:
                - k8s-dashboard.minikube.local
              ingressClassName: nginx
              useDefaultAnnotations: true
              pathType: Prefix
              path: /
              issuer:
                name: selfsigned
                scope: default
              tls:
                enabled: true
                secretName: ""
              labels: {}
              annotations: {}
            tolerations: []
            affinity: {}
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
