apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "playground-k8s"
  namespace: argocd
spec:
  description: Playground K8s
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - https://github.com/filipegalo/playground_k8s.git
  destinations:
    - name: in-cluster
      namespace: "*"
      server: https://kubernetes.default.svc
status: {}
