serviceAccounts:
  - name: admin-user
    namespace: k8s-dashboard
    clusterRole: cluster-admin
    subjects:
      - kind: ServiceAccount
        name: admin-user
        namespace: k8s-dashboard

secrets:
  - name: admin-user
    namespace: k8s-dashboard
    annotations:
      kubernetes.io/service-account.name: "admin-user"
    type: kubernetes.io/service-account-token

argocd_projects:
  - name: "playground-k8s"
    namespace: argocd
    description: Playground K8s
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    namespaceResourceWhitelist:
      - group: "*"
        kind: "*"
    sourceRepos:
      - https://github.com/filipegalo/playground_k8s.git
    destinations:
      - name: in-cluster
        namespace: "*"
        server: https://kubernetes.default.svc
